name: Release

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'dist/pixi3d.js'
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      